### PR TITLE
Loading-into-R

### PR DESCRIPTION
**Pull request by KyleBolduc**
Amended comments, made paths relative, added excel sheet merge @ed-nykaza

### CODE REVIEW

**Comment by ed-nykaza** [comment]
@KyleBolduc code looks good. I think we should make some minor tweaks before we push to master. 1) I would save this example in a folder examples/load-data-into-R/
2) I would include a readme file
3) each script should have a header and BSD2 clause. See our data science process doc for an example
4) these examples might work better in a jupyter notebook, or actually, it might be nice to have the jupyter notebook version and the R Studio version.
5) I would update your preferences in R Studio (preferences, code, diagnositcs), and would check all fo the boxes as there are a few minor things (like spaces before/after operators) and after commas that will be highlighted for review.

**Comment by ed-nykaza** [comment]
@KyleBolduc everything looks good. Before I approve for merging, can you update your jupyter notebook to have a relative path to the files. I believe you have a few bits of your local path hard coded. Also, if the juypter notebook is doing the same function as the R studio code, then I would give them the same file name.

**Comment by KyleBolduc** [comment]
@ed-nykaza Modified both initial loading pathway and final save pathway to relative path.

**Comment by ed-nykaza** [comment]
@KyleBolduc LGTM :shipit:

**Comment by KyleBolduc** [comment]
Merge completed!

**Pull request merged**
